### ISSUE TITLE
webhook

### ISSUE THREAD

**Issue by reztufirda** [kalyanraju/Bujji-Potato#1]
hi. what kind of url should I enter for the webhook? same as my game url?

**Comment by kalyanraju** [comment]
no it should be your script url where you process the data you get from different actions, ideally it should be a php script.

**Comment by reztufirda** [comment]
btw can the game in the build folder be played? I tried pressing all the buttons but no luck. haha

**Comment by kalyanraju** [comment]
game might not work as of now, it was written in a very old version of gdevelop, telegram bot will work though.

**Comment by reztufirda** [comment]
ty bro ✌🏻
